travis:
  secure:
    BINSTAR_TOKEN: Qhq7gAl5ABsjXH5szoSwhrDsMkVIfjAjy5jqSoiDwa8DiQOx1xapWFarvtgmrIug9K/CTiHWoMWQ+RaGylPG7MaT0SNbzd45UP//fRRzs/fiRpEH+7AeEbvP5JvoFMzaJhg0C4BKpyUu6LPjA0z6hvi+pTQved/8YJo0rqBBNZ9qfbrNVuyUBTGxGFqyMwFGly7bk7/ZoJW/UT/s6G7kl6LudtwsBudGwTNFupuV5Jda5j8qpFKJ8h+TV49hZDz6O3SEio4ZMd2Jtjrr71hSYX/7L+meBtieV8ellP6yNYioWux3aBWI7060/749fgzahFJFH30ya7keQk+87HoD+jqz0HCef5q7km6uMb+qNE/l34JN4rRrR6ydXiCbQ9xYbq/AiFYw45/Pjwolme4olbXykVM024bgz7ugBgFsId2Nm49M5hLpJozQgqeABD07Y5IGF6ow+XjmeFMbJAwzOKZy22en5HQHUyAr3OIDojHXxi+tbj//FV1B5XLFseT9CEkrrAOUejAG42hqZCUbs2ib8hMd1du+9It3Jp+HxMkyFfLOGdBw58QpaEl0ceh61v/gr9AQyFvfLl9/xz3/csTAEW+812CPHsOnjfDeNetFsjRT9Qh0SxpZTHaOvnV7X2pVX3y12TfG4HWoz7H2RoEcxaxVxivtjPbx45c8grU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
